openapi: "3.0.2"
info:
  title: Statistiques
  description: API pour la gestion des statistiques joueurs pour le projet Asteroids Warrior
  version: "1.0"
servers:
  - url: https://stats.aw.alexandre-vogel.fr/


#tags:
#  - name : ...
#  - description : ...

paths:
  /stats:
    post:
      tags:
        - Statistiques
      summary: Envoie une liste de statistiques joueurs
      description: Envoie une liste de statistiques joueurs
      parameters:
        - in: header
          name: serverToken
          schema:
            type: string
          required: true
          description: Token pour identifier le serveur
      requestBody:
        content:
          json:
            schema:
              type: array
              description: Liste de statistiques joueurs
              items:
                $ref: '#/components/schemas/userStats'
      responses:
        "200":
          description: Envoi réalisé avec succès
        "403":
          description: Vous n'êtes pas autorisé à modifier ces statistiques

  /stats/{idUser}:
    put:
      tags:
        - Statistiques
      summary: Modifie les statistiques d'un joueur
      description: Modifie les statistiques d'un joueur
      parameters:
        - in: header
          name: serverToken
          schema:
            type: string
          required: true
          description: Token pour identifier le serveur
        - in: path
          name: idUser
          schema:
            type: string
          required: true
          description: Id du joueur dont les statistiques doivent être modifiées
      requestBody:
        content:
          json:
            schema:
              $ref: '#/components/schemas/userStats'
      responses:
        "200":
          description: Modification réalisée avec succès
        "403":
          description: "Vous n'êtes pas autorisé à modifier ces statistiques"
        "404":
          description: "L'utilisateur demandé n'a pas été trouvé"


  /ranking/{stat}:
    get:
      tags:
        - Classement
      summary: Récupère le classement des joueurs
      description: Récupère le classement basé sur une statistique particulière
      parameters:
        - in: path
          name: stat
          schema:
            type: string
          required: true
          description: Statistique sur laquelle doit être basée le classement
        - in: query
          name: offset
          schema:
            type: number
            minimum: 1
          required: false
          description: Rang du premier joueur de la liste
        - in: query
          name: limit
          schema:
            type: number
            minimum: 1
          required: false
          description: Taille de la liste
      responses:
        "200":
          description: Le classement a été récupéré et est transmis dans le corps du message
          content:
            json:
              schema:
                type: array
                description: Classement des joueurs
                items: 
                  $ref: '#/components/schemas/userStats'
        "400":
          description: "Requête invalide : l'un des champs est incorrect"
          
  /stats:
    get:
      tags :
        - Statistiques
      summary: Récupère les statistiques de tous les joueurs
      description: Permet de récupérer l'ensemble des statistiques de tous les joueurs
      responses: 
        "200" :
          description: L'ensemble du classement a été récupéré et est transmis dans le corps du message
          content:
            json:
              schema:
                type: array
                description: Ensemble des statistiques
                items:
                  $ref: '#/components/schemas/userStats'
  
          
  /stats/{idUser}:
    get:
      tags:
        - Statistiques
      summary: Récupère les statistiques d'un utilisateur
      description: Permet de récupérer l'ensemble des statistiques d'un utilisateur 
      parameters: 
        - name: idUser
          in: path
          description: ID de l'utilisateur recherché
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: L'ensemble des statistiques du joueur avec l'ID spécifié ont été récupérées
          content:
            json:
              schema:
                $ref: '#/components/schemas/userStats'
        "404":
          description: L'utilisateur demandé n'a pas été trouvé
        
        
    post:
      tags:
        - Statistiques
      summary: Modifie les statistiques d'un utilisateur
      description: Permet, à la fin d'une partie de mettre à jour les statistiques d'un utilisateur précis
      parameters: 
        - name: idUser
          in: path
          description: ID de l'utilisateur recherché
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: L'ensemble des statistiques du joueur avec l'ID spécifié ont été mises à jour
        "403":
          description: Vous n'êtes pas autorisé à modifier ces statistiques
       "404":
          description: L'utilisateur demandé n'a pas été trouvé
        
              
    


components:
  schemas:
    userStats:
      type: object
      properties:
        username:
          type: string
          example: "johndoe"
        nbKills:
          type: number
          minimum: 0
          example: 1021
        nbAsteroids:
          type: number
          minimum: 0
          example: 39281
        nbPoints:
          type: number
          minimum: 0
          example: 2921213
        nbDeaths:
          type: number
          minimum: 0
          example: 2012
        nbPowerUps:
          type: number
          minimum: 0
          example: 821
        nbGames:
          type: number
          minimum: 0
          example: 210
        nbWins:
          type: number
          minimum: 0
          example: 102
        maxKills:
          type: number
          minimum: 0
          example: 13
        maxPoints:
          type: number
          minimum: 0
          example: 768
        maxPowerUps:
          type: number
          minimum: 0
          example: 11
        maxDeaths:
          type: number
          minimum: 0
          example: 23


        

            

